apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pattern-pod
spec:
  containers:
    - name: main-container
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args: ["while true; do echo hello $(date)  >> /var/my-volume-directory/my-volume-file.txt; sleep 2; done;"]
      volumeMounts:
        - mountPath: /var/my-volume-directory
          name: my-volume
    - name: sidecar-container
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args: ["while true; do cat /var/my-volume-directory/my-volume-file.txt; sleep 5; done;"]
      volumeMounts:
        - mountPath: /var/my-volume-directory
          name: my-volume
  volumes:
    - name: my-volume
      emptyDir: {}
